<?php

namespace AppBundle\Repository;

/**
 * SupportRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupportRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
